
name: build_push

on: [push]

jobs:
  run_molecule_test:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        distro:
          - image: alpine
            version: "3.17"
            platform: "linux/amd64"
            tags: "3.17"
          - image: alpine
            version: "3.18"
            tags: "3.18"
          - image: alpine
            version: "3.19"
            tags: "3.19"
          - image: alpine
            version: "3.20"
            tags: "3.20"
          - image: alpine
            version: "3.21"
            tags: "3.21,latest"
    uses: hybridadmin/reuse-workflows/.github/workflows/build_push.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tags: '${{ matrix.distro.tags }}'
      distro_platform: 'linux/amd64,linux/arm64'
      distro_version: '${{ matrix.distro.version }}'

  run_update_readme:
    needs:
      - run_molecule_test
    uses: hybridadmin/reuse-workflows/.github/workflows/update_readme.yml@main
    secrets: inherit
    with:
      repo_name: 'hybridadmin/ansible-alpine'
