name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: alpine
            version: "edge"
            platform: "linux/amd64"
          - image: alpine
            version: "3.10"
            platform: "linux/amd64"
          - image: alpine
            version: "3.11"
            platform: "linux/amd64"
          - image: alpine
            version: "3.12"
            platform: "linux/amd64"
          - image: alpine
            version: "3.13,latest"
            platform: "linux/amd64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.24.8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker build \
            --no-cache \
            --rm \
            --file=${{ matrix.distribution.version }}/Dockerfile \
            $(for i in $(echo ${{ matrix.distribution.version }} | sed "s/,/ /g"); do echo "--tag hybridadmin/${{ matrix.distribution.image }}:$i "; done) \
            ansible-${{ matrix.distribution.image }}

      - name: Test Docker images
        run: |
          container_id=$(mktemp)
          sudo docker run \
            --detach \
            --privileged \
            -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
            hybridadmin/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} > "${container_id}"
          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})

      - name: Build Docker images on all platforms
        run: |
          docker buildx build \
            --platform ${{ matrix.distribution.platform }} \
            --file=${{ matrix.distribution.version }}/Dockerfile \
            $(for i in $(echo ${{ matrix.distribution.version }} | sed "s/,/ /g"); do echo "--tag hybridadmin/${{ matrix.distribution.image }}:$i "; done) \
            ansible-${{ matrix.distribution.image }}

